[code]
Com_Printf = 0x28f
CG_Argv = 0x2ac
UpdateTimer = 0x5fd7
CG_DrawStrlen = 0x1d514
strlen = 0x2f24d
tan = 0x2f3f5
atoi = 0x2f5b8
sscanf = 0x2fb43
Distance = 0x308c9
AxisClear = 0x30f74
VectorRotate = 0x31135
Com_Clamp = 0x31df1
COM_Parse = 0x31f8b
Q_strncpyz = 0x324a6
Q_stricmp = 0x325be
va = 0x32755
# ----------------------------- SYSCALLS -----------------------------
acos = -112
testPrintFloat = -111
testPrintInt = -110
ceil = -109
floor = -108
sqrt = -107
atan2 = -106
cos = -105
sin = -104
strncpy = -103
memcpy = -102
memset = -101
trap_FS_Seek = -90
trap_R_inPVS = -89
trap_R_AddPolysToScene = -88
trap_GetEntityToken = -87
trap_R_AddAdditiveLightToScene = -86
trap_CM_TransformedCapsuleTrace = -85
trap_CM_CapsuleTrace = -84
trap_CM_TempCapsuleModel = -83
trap_S_StopLoopingSound = -82
trap_S_AddRealLoopingSound = -81
trap_R_RemapShader = -80
trap_CIN_SetExtents = -79
trap_CIN_DrawCinematic = -78
trap_CIN_RunCinematic = -77
trap_CIN_StopCinematic = -76
trap_CIN_PlayCinematic = -75
trap_R_LightForPoint = -74
trap_RemoveCommand = -73
trap_SnapVector = -72
trap_RealTime = -71
trap_S_StopBackgroundTrack = -70
trap_PC_SourceFileAndLine = -69
trap_PC_ReadToken = -68
trap_PC_FreeSource = -67
trap_PC_LoadSource = -66
trap_PC_AddGlobalDefine = -65
trap_Key_GetKey = -64
trap_Key_SetCatcher = -63
trap_Key_GetCatcher = -62
trap_Key_IsDown = -61
trap_R_RegisterFont = -60
trap_MemoryRemaining = -59
trap_R_RegisterShaderNoMip = -58
trap_SetUserCmdValue = -57
trap_GetUserCmd = -56
trap_GetCurrentCmdNumber = -55
trap_GetServerCommand = -54
trap_GetSnapshot = -53
trap_GetCurrentSnapshotNumber = -52
trap_GetGameState = -51
trap_GetGlconfig = -50
trap_R_LerpTag = -49
trap_R_ModelBounds = -48
trap_R_DrawStretchPic = -47
trap_R_SetColor = -46
trap_R_RenderScene = -45
trap_R_AddLightToScene = -44
trap_R_AddPolyToScene = -43
trap_R_AddRefEntityToScene = -42
trap_R_ClearScene = -41
trap_R_RegisterShader = -40
trap_R_RegisterSkin = -39
trap_R_RegisterModel = -38
trap_R_LoadWorldMap = -37
trap_S_StartBackgroundTrack = -36
trap_S_RegisterSound = -35
trap_S_Respatialize = -34
trap_S_UpdateEntityPosition = -33
trap_S_AddLoopingSound = -32
trap_S_ClearLoopingSounds = -31
trap_S_StartLocalSound = -30
trap_S_StartSound = -29
trap_CM_MarkFragments = -28
trap_CM_TransformedBoxTrace = -27
trap_CM_BoxTrace = -26
trap_CM_TransformedPointContents = -25
trap_CM_PointContents = -24
trap_CM_TempBoxModel = -23
trap_CM_LoadModel = -22
trap_CM_InlineModel = -21
trap_CM_NumInlineModels = -20
trap_CM_LoadMap = -19
trap_UpdateScreen = -18
trap_SendClientCommand = -17
trap_AddCommand = -16
trap_SendConsoleCommand = -15
trap_FS_FCloseFile = -14
trap_FS_Write = -13
trap_FS_Read = -12
trap_FS_FOpenFile = -11
trap_Args = -10
trap_Argv = -9
trap_Argc = -8
trap_Cvar_VariableStringBuffer = -7
trap_Cvar_Set = -6
trap_Cvar_Update = -5
trap_Cvar_Register = -4
trap_Milliseconds = -3
trap_Error = -2
trap_Print = -1
# --------------------------- SYSCALLS END ---------------------------

[hooks]
CG_RegisterCvars = 0xfb
CG_UpdateCvars = 0x19e
CG_Init = 0xdc1
CG_Draw2D_df = 0x2a12
CG_DrawActive = 0x1ce20
CG_AddCEntity = 0x1f222
CG_ConsoleCommand = 0x1ad89
CG_InitConsoleCommands = 0x1adc7

[data]
bg_itemlist = 0x3748
cg = 0xcfcc8
cgs = 0xee75c
sv_cheats = 0x11d40c
timer_time = 0x11d77c