default_install_hook_types: [pre-commit, post-rewrite, post-merge, post-checkout]
default_stages: [pre-commit, post-rewrite, post-merge]

repos:
  - repo: local
    hooks:
      - id: uv-sync
        name: uv-sync
        description: "Automatically run 'uv sync' on your repository after a checkout, pull or rebase"
        entry: uv sync --no-active
        args: ["--locked"]
        language: python
        always_run: true
        pass_filenames: false
        stages: [post-checkout, post-merge, post-rewrite]
        minimum_pre_commit_version: "2.9.2"

      - id: ruff-check
        name: ruff check
        description: "Run 'ruff check' for extremely fast Python linting"
        entry: uv run ruff check --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: ruff-format
        name: ruff format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: uv run ruff format --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"
      
      - id: format-symbols
        name: format symbols
        description: "Format project symbols"
        entry: uv run scripts/format_symbols.py
        language: unsupported
        files: ^src/.+/symbols\.toml$
        args: []
        additional_dependencies: []

  # This should be before cpp-linter-hooks as that needs this
  - repo: local
    hooks:
      - id: generate-compile-commands
        name: generate compile_commands.json
        entry: uv run build.py compile-commands
        language: unsupported
        always_run: true
        pass_filenames: false
        require_serial: true
        fail_fast: true
        stages: [pre-commit, post-rewrite, post-merge, post-checkout]

  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v1.5.0
    hooks:
      - id: clang-format
        args: [--style=file, --version=22.1]
      - id: clang-tidy
        # This hook doesn't respect our inner .clang-tidy, so we have to filter it here again.
        files: ^src/(?!third_party/).*$
        args: [--compile-commands=., --checks=.clang-tidy, --allow-no-checks, --version=22.1, --fix, -fix-errors]
